---
- name: Build the Avimetrics container
  hosts: metrics_hosts
  become: True

  tasks:
    - name: archive directory to copy
      archive:
        path:
          - "{{ playbook_dir }}/dockerfile"
          - "{{ playbook_dir }}/appdynamics_http.json"
          - "{{ playbook_dir }}/avi_controllers.json"
          - "{{ playbook_dir }}/avimetrics-create.yml"
          - "{{ playbook_dir }}/avimetrics-delete.yml"
          - "{{ playbook_dir }}/avimetrics.py"
          - "{{ playbook_dir }}/datadog.json"
          - "{{ playbook_dir }}/graphite_host.json"
          - "{{ playbook_dir }}/metrics_endpoints.py"
          - "{{ playbook_dir }}/splunk_host.json"
        dest: "{{ playbook_dir }}/avimetrics.tgz"
      delegate_to: 127.0.0.1
      when: (inventory_hostname != "localhost")

    - name: copy files
      copy:
        src: "{{ playbook_dir }}/avimetrics.tgz"
        dest: "./"
        remote_src: no
        force: no
      when: (inventory_hostname != "localhost")

    - name: unarchive files to build container
      unarchive:
        src: avimetrics.tgz
        dest: .
      when: (inventory_hostname != "localhost")

    - name: build the avimetrics base image
      docker_image:
        path: .
        name: avimetrics
        tag: latest
        state: present

    - name: start avimetrics
      docker_container:
        name: avimetrics
        hostname: avimetrics
        networks:
           - name: avinet
             ipv4_address: "169.254.100.102"
        env:
            EN_METRIC_ENDPOINT: influxdb
        log_driver: json-file
        log_options:
            max-size: 1m       
        purge_networks: yes
        detach: yes
        restart_policy: always
        state: started
        image: avimetrics:latest




    - name: cleanup remote files
      file:
          path: "{{ item }}"
          state: absent
      with_items:
          - ./avimetrics.tgz
          - ./dockerfile
          - ./appdynamics_http.json
          - ./avi_controllers.json
          - ./avimetrics-create.yml
          - ./avimetrics-delete.yml
          - ./avimetrics.py
          - ./datadog.json
          - ./graphite_host.json
          - ./metrics_endpoints.py
          - ./splunk_host.json
      when: (inventory_hostname != "localhost")
