avi_config:
  alertsyslogconfig:
    - name: syslog-servers
      syslog_servers:
          - udp: true
            syslog_server_port: 1514
            syslog_server: splunk.avinet


  actiongroupconfig:
    - name: "System-Alert-Level-High"
      syslog_config_ref: "/api/alertsyslogconfig?name=syslog-servers"
      level: ALERT_HIGH
      external_only: false
    - name: "System-Alert-Level-Medium"
      syslog_config_ref: "/api/alertsyslogconfig?name=syslog-servers"
      level: ALERT_MEDIUM
      external_only: false
    - name: "System-Alert-Level-Low"
      syslog_config_ref: "/api/alertsyslogconfig?name=syslog-servers"
      level: ALERT_LOW
      external_only: false
    - name: "Syslog-System"
      syslog_config_ref: "/api/alertsyslogconfig?name=syslog-servers"
      level: ALERT_LOW
      external_only: false
    - name: "Syslog-Config"
      syslog_config_ref: "/api/alertsyslogconfig?name=syslog-servers"
      level: ALERT_LOW
      external_only: false





  alertconfig:
    - name: Avi-High
      expiry_time: 86400
      enabled: true
      category: REALTIME
      level: ALERT_HIGH
      rolling_window: 300
      source: EVENT_LOGS
      threshold: 1
      throttle: 0
      action_group_ref: "/api/actiongroupconfig?name=System-Alert-Level-High"
      alert_rule:
        operator: "OPERATOR_OR"
        sys_event_rule:
            - event_id: CACHE_OBJ_ALLOC_FAIL
              not_cond: false
            - event_id: CC_CLUSTER_VIP_DECONFIG_FAILURE
              not_cond: false
            - event_id: CC_DELETE_VIP_FAILURE
              not_cond: false
            - event_id: CC_GENERIC_FAILURE
              not_cond: false
            - event_id: CC_IP_DETACH_FAILURE
              not_cond: false
            - event_id: CC_SE_DELETION_FAILURE
              not_cond: false
            - event_id: CC_TENANT_INIT_FAILURE
              not_cond: false
            - event_id: CC_VIP_DNS_DEREGISTER_FAILURE
              not_cond: false
            - event_id: CC_VNIC_DELETION_FAILURE
              not_cond: false
            - event_id: CONN_DROP_MAX_FLOW_TBL
              not_cond: false
            - event_id: CONN_DROP_MAX_PERSIST_TBL
              not_cond: false
            - event_id: CONN_DROP_MAX_SYN_TBL
              not_cond: false
            - event_id: CONN_DROP_NO_CONN_MEM
              not_cond: false
            - event_id: CONN_DROP_NO_PKT_BUFF
              not_cond: false
            - event_id: CONTROLLER_NODE_SHUTDOWN
              not_cond: false
            - event_id: CONTROLLER_SERVICE_CRITICAL_FAILURE
              not_cond: false
            - event_id: CONTROLLER_SERVICE_FAILURE
              not_cond: false
            - event_id: CREATE_SE_FAIL
              not_cond: false
            - event_id: CREATE_SE_TIMEOUT
              not_cond: false
            - event_id: GS_DOWN
              not_cond: false
            - event_id: IP_POOL_EXHAUSTED
              not_cond: false
            - event_id: METRICS_DB_DISK_FULL
              not_cond: false
            - event_id: MODIFY_NW_FAIL
              not_cond: false
            - event_id: NO_HOST_AVAIL
              not_cond: false
            - event_id: PKT_BUFF_ALLOC_FAIL
              not_cond: false
            - event_id: PKT_DROP_NO_PKT_BUFF
              not_cond: false
            - event_id: POOL_AUTO_DEPLOYMENT_FAILED
              not_cond: false
            - event_id: REBOOT_SE
              not_cond: false
            - event_id: SCHEDULER_ACTION_FAILURE
              not_cond: false
            - event_id: SE_CONN_MEM_HIGH
              not_cond: false
            - event_id: SE_CPU_HIGH
              not_cond: false
            - event_id: SE_DISK_HIGH
              not_cond: false
            - event_id: SE_EXTERNAL_HM_RESTART
              not_cond: false
            - event_id: SE_FLOW_TBL_HIGH
              not_cond: false
            - event_id: SE_GEO_DB_FAILURE
              not_cond: false
            - event_id: SE_HEARTBEAT_FAILURE
              not_cond: false
            - event_id: SE_MEM_HIGH
              not_cond: false
            - event_id: SE_PERSIST_TBL_HIGH
              not_cond: false
            - event_id: SE_PKT_BUFF_HIGH
              not_cond: false
            - event_id: SE_SYN_CACHE_USAGE_HIGH
              not_cond: false
            - event_id: SE_SYN_TBL_HIGH
              not_cond: false
            - event_id: SE_VNIC_DHCP_IP_ALLOC_FAILURE
              not_cond: false
            - event_id: SE_VNIC_DOWN_EVENT
              not_cond: false
            - event_id: SE_VNIC_DUPLICATE_IP
              not_cond: false
            - event_id: SE_VNIC_TX_QUEUE_STALL
              not_cond: false
            - event_id: VS_CONN_LIMIT
              not_cond: false
            - event_id: VS_GEO_DB_FAILURE
              not_cond: false
            - event_id: VS_SE_BOOTUP_FAIL
              not_cond: false
            - event_id: VS_SE_IP_FAIL
              not_cond: false
            - event_id: VS_THROUGHPUT_LIMIT
              not_cond: false

    - name: Avi-Medium
      expiry_time: 86400
      enabled: true
      category: REALTIME
      level: ALERT_MEDIUM
      rolling_window: 300
      source: EVENT_LOGS
      threshold: 1
      throttle: 0
      action_group_ref: "/api/actiongroupconfig?name=System-Alert-Level-Medium"
      alert_rule:
        operator: "OPERATOR_OR"
        sys_event_rule:
            - event_id: CC_SE_DELETION_DETECTED
              not_cond: false
            - event_id: CONTROLLER_LEADER_FAILOVER
              not_cond: false
            - event_id: CONTROLLER_SERVICE_RESTORED
              not_cond: false
            - event_id: DELETE_SE_FAIL
              not_cond: false
            - event_id: DUPLICATE_SUBNETS
              not_cond: false
            - event_id: GS_GROUP_DOWN
              not_cond: false
            - event_id: LS_IMAGE_UPLOAD_FAILURE
              not_cond: false
            - event_id: MIGRATE_SE_FAILED
              not_cond: false
            - event_id: SERVER_AUTOSCALE_IN_FAILED
              not_cond: false
            - event_id: SERVER_AUTOSCALE_OUT_FAILED
              not_cond: false
            - event_id: UPGRADE_SE_SUSPENDED
              not_cond: false
            - event_id: UPGRADE_SE_VS_DISRUPTED
              not_cond: false
            - event_id: VS_AWAITING_SE
              not_cond: false
            - event_id: VS_MIGRATE_FAILED
              not_cond: false
            - event_id: VS_SCALEIN_FAILED
              not_cond: false
            - event_id: VS_SCALEOUT_FAILED
              not_cond: false
            - event_id: VS_SWITCHOVER_FAIL
              not_cond: false


    - name: Avi-Catchall
      expiry_time: 86400
      enabled: true
      category: REALTIME
      level: ALERT_LOW
      rolling_window: 300
      source: EVENT_LOGS
      threshold: 1
      throttle: 0
      action_group_ref: "/api/actiongroupconfig?name=System-Alert-Level-Low"
      alert_rule:
          operator: "OPERATOR_OR"



  analyticsprofile:
    - name: System-Analytics-Profile
      client_log_streaming_config:
          max_logs_per_second: 100
          external_server_port: 1515
          log_types_to_send: LOGS_ALL
          external_server: splunk.avinet
