---
- hosts: controllers
  become: yes
  vars_files:
    - ../vars/avi_details.yaml
  roles:
    - avinetworks.avisdk

  tasks:

    - name: Wait for Avi Controller services to be ready
      wait_for:
        port: 443
        host: "{{ ansible_default_ipv4.address }}"
        connect_timeout: 3
        delay: 5
        timeout: 600

    - name: Wait for Avi Controller API
      uri: url="https://{{ controller_ip}}/" return_content=yes validate_certs=False
      validate_certs: no
      register: srvc_results
      until: srvc_results.status == 200
      retries: 20
      delay: 5
      ignore_errors: yes


    - name: Wait for Avi Controller API
      uri: url="https://{{ controller_ip}}/login" return_content=yes validate_certs=False
      method: POST
      validate_certs: no
      register: tmp_results
      until: tmp_results.status == 401
      retries: 20
      delay: 5
      ignore_errors: yes


    - avi_api_session:
        api_version: "{{ api_version }}"
        controller: "{{ controller_ip }}"
        username: "{{ username }}"
        password: "{{ password }}"
        tenant: "{{ tenant | default('admin',true) }}"
        http_method: get
        path: tenant
        params:
          name: "admin"
      register: api_results
      until: api_results|selectattr("results.obj.count", "defined")
      #until: api_results.results.obj.count is defined
      retries: 20
      delay: 30
      ignore_errors: yes
