---
- name: Build the Graphite Container
  hosts: metrics_hosts
  become: True

  tasks:
    - name: archive directory to copy
      archive:
        path:
          - "{{ playbook_dir }}/dockerfile"
          - "{{ playbook_dir }}/storage-schemas.conf"
        dest: "{{ playbook_dir }}/graphite.tgz"
      delegate_to: 127.0.0.1
      when: (inventory_hostname != "localhost")

    - name: copy files
      copy:
        src: "{{ playbook_dir }}/graphite.tgz"
        dest: "./"
        remote_src: no
        force: no
      when: (inventory_hostname != "localhost")

    - name: unarchive files to build container
      unarchive:
        src: graphite.tgz
        dest: .
      when: (inventory_hostname != "localhost")

    - name: build the graphite base image
      docker_image:
        path: .
        name: graphite
        tag: latest
        state: present

    - name: start the graphite container
      docker_container:
        name: graphite
        hostname: graphite
        networks:
           - name: avinet
             ipv4_address: "169.254.100.100"
        purge_networks: yes
        volumes: graphite-data:/opt/graphite/storage
        log_driver: json-file
        log_options:
            max-size: 200m
        detach: yes
        restart_policy: always
        state: started
        image: graphite:latest


    - name: cleanup remote files
      file:
          path: "{{ item }}"
          state: absent
      with_items:
          - ./graphite.tgz
          - ./dockerfile
          - ./storage-schemas.conf
      when: (inventory_hostname != "localhost")
