- hosts: service_engines
  become: yes
  vars_files:
    - "../vars/creds.yml"
    - "vars/hosts.yml"
  tasks:
  - name: Check if Avi user is present on SE
    stat: path=/etc/sudoers.d/aviuser
    register: sudoers_file_exists

  - name: Setup SSH user for SE
    shell: curl -ks https://{{ controller }}/api/linux_host_install?username={{ linuxserver_configuration.ssh_attr.ssh_user }} | sudo bash
    when: sudoers_file_exists.stat.exists == False
